language: go

go:
  - 1.7

install:
    - go get -t -v ./...

script:
    - go vet -x
    - go install
    - go test -race -coverprofile=coverage.txt -covermode=atomic -v

after_success:
    - bash <(curl -s https://codecov.io/bash)